all:
  children:
    production:
      hosts:
        krolikkanban-prod:
          ansible_host: your-production-server.com
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          supabase_url: "https://your-project.supabase.co"
          supabase_anon_key: "your-supabase-anon-key"
          nextauth_secret: "your-nextauth-secret"
          app_url: "https://krolikkanban.example.com"
    
    staging:
      hosts:
        krolikkanban-staging:
          ansible_host: your-staging-server.com
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          supabase_url: "https://your-staging-project.supabase.co"
          supabase_anon_key: "your-staging-supabase-anon-key"
          nextauth_secret: "your-staging-nextauth-secret"
          app_url: "https://staging.krolikkanban.example.com"
    
    development:
      hosts:
        krolikkanban-dev:
          ansible_host: your-dev-server.com
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          supabase_url: "https://your-dev-project.supabase.co"
          supabase_anon_key: "your-dev-supabase-anon-key"
          nextauth_secret: "your-dev-nextauth-secret"
          app_url: "http://localhost"